### ISSUE TITLE
Cash flow api attribute error

### ISSUE THREAD

**Issue by kesh-hrishi** [tornotron/Investment-Automation-App#1]
https://i.imgur.com/WNsO5fp.png

API documentation link : https://www.alphavantage.co/documentation/

**Comment by abhijithanandan** [comment]
![image](https://user-images.githubusercontent.com/30103817/229554997-0012f103-2329-45cd-a00e-2a8aade76e66.png)

Take a look at the implementation of cash flow; it is different from what we have done.
